import React from 'react'
import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/images/profile/Foto web.png'

export default function Home() {
	return (
		<>
			<Head>
				<title>OE</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full   min-h-screen'>
				<Layout className='pt-1'>
					<div className='flex items-center justify-between w-full'>
						<div className='w-3/12 ml-20'>
							<Image src={profilePic} alt='' className='w-full h-auto' />
						</div>
						<div className='w-1/2 flex flex-col items-center self-center'>
							<AnimatedText
								text='Привет, рад видеть вас на моей странице.'
								className='text-5xl text-left'
							/>
							<p className='my-2 text-base font-medium'>
								Как опытный разработчик, я стремлюсь воплощать идеи в
								приложения. Ознакомьтесь с моими последними проектами,
								демонстрирующими мой опыт в React.js и веб-разработке.
							</p>
							<div className='flex item-center self-start mt-3'>
								<Link
									href='/CV.pdf'
									target={'_blank'}
									className='flex items-center bg-dark text-light p-2.5 px-4 
                                      rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                                      border-2 border-solid border-transparent hover:border-dark'
									download={true}
								>
									Резюме <LinkArrow className={'w-6 ml-1'} />
								</Link>
								<Link
									href='mailto:https://mail.google.com/mail/u/0/#inbox'
									target={'_blank'}
									className='ml-4 mt-3 text-lg font-medium capitalize text-dark underline'
								>
									Контакт
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
			</main>
		</>
	)
}