import React from 'react'
import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/image/profile/Foto web.png'

export default function Home() {
	return (
		<>
			<Head>
				<title>OE</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
				<Layout className='pt-0 md:p-16 sm:pt-8'>
					<div className='flex items-center justify-between w-full lg:flex-col'>
						<div className='w-2/2 ml-5 md:w-full'>
							<Image src={profilePic} alt="" className='w-full h-auto lg:hidden md:inline-block md:w-full' 
							priority
							sizes="(max-width: 768px) 100vw,
							       (max-width: 1200px) 50vw,
							         50vw
									"/>
						</div>
						<div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
							<AnimatedText
								text='Привет, рад видеть вас на моей странице.'
								className='text-5xl text-left xl:!text-5xl lg:!text-center lg:!text=5xl md:!text-5xl sm:!text-3xl'
							/>
							<p className='my-2 text-base font-medium md:text-sm sm:text-xs'>
								Как опытный разработчик, я стремлюсь воплощать идеи в
								приложения. Ознакомьтесь с моими последними проектами,
								демонстрирующими мой опыт в React.js и веб-разработке.
							</p>
							<div className='flex item-center self-start mt-3 lg:self-center'>
								<Link
									href='/CV.pdf'
									target={'_blank'}
									className="flex items-center bg-dark text-light p-2.5 px-4 
                                      rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                                      border-2 border-solid border-transparent hover:border-dark
									  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
									  md:p-2 md:px-4 md:text-base"
									download={true}
								>
									Резюме <LinkArrow className={'w-6 ml-1'} />
								</Link>
								<Link
									href='mailto:omarowsky.e@gmail.com'
									target={'_blank'}
									className='ml-4 mt-3 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
								>
									Связаться со мной
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
			</main>
		</>
	)
}